version: "3"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - pgdata:/var/lib/postgresql/data/
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    network_mode: host
volumes:
  pgdata:
    
